### ISSUE TITLE
Enemies use their TP moves at incorrect intervals without regard for their current HP%

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#1032] opened 2020-08-29 03:38 UTC
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://ffxiclopedia.fandom.com/wiki/Tactical_Points
"Monsters will use their TP semi-randomly when at 25% HP or above, until reaching 3000 TP at which point they will use it on one of their special attacks. Once monsters fall below 25% HP, they will no longer save their TP and will attempt to use their special attacks immediately upon reaching 1000 TP."

This is supposedly part of issue #184 as discussed in the last 1/3 of it, but that issue is very unclear and can likely be closed.

**Comment by tankfest** [comment] 2020-08-31 04:04
I found the offending code; in the function CMobController::DoCombatTick:
```else if (m_Tick >= m_LastMobSkillTime && tpzrand::GetRandomNumber(100) < PMob->TPUseChance() && MobSkill())```
which leads us to ``TPUseChance()``
```
uint8 CMobEntity::TPUseChance()
{
    auto& MobSkillList = battleutils::GetMobSkillList(getMobMod(MOBMOD_SKILL_LIST));

    if (health.tp < 1000 || MobSkillList.empty() == true || !static_cast<CMobController*>(PAI->GetController())->IsWeaponSkillEnabled())
    {
        return 0;
    }

    if (health.tp == 3000 || (GetHPP() <= 25 && health.tp >= 1000))
    {
        return 100;
    }

    return (uint8)getMobMod(MOBMOD_TP_USE_CHANCE);
}
```
MOBMOD_TP_USE_CHANCE defaults to 30 in mobutils.cpp if it's not normally set... but obviously this isn't working as intended.

**Comment by TeoTwawki** [comment] 2020-08-31 11:44
so it looks like what happened is back when the tickrate was made a shorter time interval that caused the use chance check to fire more often, leading to more frequent tp use at the same hp/tp amounts.

**Comment by zach2good** [comment] 2020-09-05 09:24
Fixed by https://github.com/project-topaz/topaz/pull/1046

**Closed as completed by zach2good** 2020-09-05 09:24 UTC

**Comment by TeoTwawki** [comment] 2020-09-05 21:44
note: there *may* still be an issue in that its unconfirmed if we should have an on tick random check *at all* but that PR put the rate of fire back where it used to be before the tick rate was changed.
