### ISSUE TITLE
Linux x64 not building with recent changes on Canary

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#713] opened 2020-06-11 18:10 UTC
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

g++ -std=c++17 -DHAVE_CONFIG_H -I. -I./src/common   -fsigned-char -DFMT_HEADER_ONLY -Wall -Werror -Wfatal-errors      -fsigned-char -I/usr/include/luajit-2.1 -I/usr/include/mysql   -fsigned-char -g -O2 -MT topaz_game-battlefield_handler.o -MD -MP -MF .deps/topaz_game-battlefield_handler.Tpo -c -o topaz_game-battlefield_handler.o `test -f 'src/map/battlefield_handler.cpp' || echo './'`src/map/battlefield_handler.cpp
src/map/entities/trustentity.cpp: In member function ‘virtual void CTrustEntity::OnCastFinished(CMagicState&, action_t&)’:
src/map/entities/trustentity.cpp:169:10: error: unused variable ‘PTarget’ [-Werror=unused-variable]
     auto PTarget = static_cast<CBattleEntity*>(state.GetTarget());
          ^~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
Makefile:2776: recipe for target 'topaz_game-trustentity.o' failed
make: *** [topaz_game-trustentity.o] Error 1
make: *** Waiting for unfinished jobs....
mv -f .deps/topaz_game-grades.Tpo .deps/topaz_game-grades.Po
mv -f .deps/topaz_game-battlefield_handler.Tpo .deps/topaz_game-battlefield_handler.Po
mv -f .deps/topaz_game-battlefield.Tpo .deps/topaz_game-battlefield.Po

**Comment by Kreidos** [comment] 2020-06-11 18:52
Issue is caused by an unused variable warning in Trust changes which were merged alongside https://github.com/project-topaz/topaz/pull/688. Individually they seem fine, but the new warning flags in the new makefile are triggering this failure.

Short-term fix for anyone in need is to revert the makefile change merge until Trusts can get an update.
`git revert -m 1 7cf5220`

**Comment by ShelbyZ** [comment] 2020-06-13 15:29
#717

**Closed as completed** 2020-06-14 01:13 UTC
